version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:4.1.3
    ports:
      - "4444:4444"

